### PR TITLE
Update ma_charsets

### PR DESCRIPTION
**Pull request by better0fdead**
Updated compiled_charset_list prior to  https://github.com/tarantool/mysql/issues/47 in tarantool/mysql repo.

### CODE REVIEW

**Comment by Totktonada** [comment]
Did you consider to update the base downstream version to the latest upstream release? (Asked in PR #1, but didn't get an answer.)

Anyway, backporting is okay for me too. I just want to understand how the decision was made.

**Review by Totktonada — APPROVED** [review]

**Comment by better0fdead** [comment]
> Did you consider to update the base downstream version to the latest upstream release? (Asked in PR #1, but didn't get an answer.)
> 
> Anyway, backporting is okay for me too. I just want to understand how the decision was made.

I thought about that, but it breaks tarantool/mysql, I think it's worth another task. For that particular issue just updating ma_charset is enough.

**Review by DifferentialOrange — COMMENTED** [review]
Thank you for the PR. Can you please provide a draft PR for mysql with charset test based on https://github.com/tarantool/mysql/issues/47 ? It is rather hard to verify these changes by reviewing the code.

**Comment by better0fdead** [comment]
> Thank you for the PR. Can you please provide a draft PR for mysql with charset test based on [tarantool/mysql#47](https://github.com/tarantool/mysql/issues/47) ? It is rather hard to verify these changes by reviewing the code.

Yes, u can see it [here](https://github.com/tarantool/mysql/pull/71), i dele ted workaround from ci for this bug, so u can see that ci is green without workaround.

**Review by DifferentialOrange — APPROVED** [review]

**Pull request merged**
